### PR TITLE
Add events metrics

### PR DESCRIPTION
**Pull request by CoRfr**
Hi,

This is to had a script that tracks the number of on-going events.
I've been using it and, well it works ;p

### CODE REVIEW

**Comment by sstarcher** [comment]
@CoRfr could you update the changelog and the readme

**Comment by CoRfr** [comment]
Hi @sstarcher , let me know if that's okay with you or if you have concerns/recommendations.
Thanks

**Comment by CoRfr** [comment]
Seems like 1.9.3 has been deprecated in https://github.com/sensu-plugins/sensu-plugin/commit/d965911eea6b6e3d3ffec7316ea2f3c68f8580a1 so I removed it from the .travis.yml (and also added 2.3.0 while I was at it).

**Comment by sstarcher** [comment]
@CoRfr thanks for those changes

**Pull request merged**
