### PR TITLE
Remove api_call event in deregister handler

### PR DESCRIPTION
**Pull request by runningman84**
## Pull Request Checklist

no
#### General
- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)
- [x] RuboCop passes
- [x] Existing tests pass 
#### Purpose

Otherwise the event list gets bigger and bigger...

### CODE REVIEW

**Comment by sstarcher** [comment]
Is this to fix #3

**Comment by runningman84** [comment]
Maybe it will help with #3 too, my experience is that event list isn't cleaned up and gets bigger and bigger with each deregister operation. My patch removes the corresponding event using the api.

@portertech is this an expected behavior?

**Comment by cwjohnston** [comment]
My understanding is that lingering events after client deregistration is likely a manifestation of timing issues related to the current implementation of client deregistration inside the init script.

In sensu/sensu#1309 we are proposing to move deregistration into the client process itself. Because we'll send a deregistration event after the client is paused, no new keepalives should be sent, and when the deregistration handler deletes the client, all events for that client should be deleted as well.

**Comment by runningman84** [comment]
ok this seems to work now

**Pull request closed without merging**
