### PR TITLE
Feature/output rotation

### PR DESCRIPTION
**Pull request by luisdavim**
## Pull Request Checklist

This is to replace #37 since the original author was not responsive.

#### General

- [x] Update Changelog following the conventions laid out on [Our CHANGELOG Guidelines ](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [x] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

Change the output message to a more standard format.

### CODE REVIEW

**Comment by majormoses** [comment]
Thanks for picking this up for the original submitter. Can you please include a [changelog entry](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md) and a [testing artifact](https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md#7-testing-artifacts) ?

**Review by majormoses — CHANGES_REQUESTED** [review]
Needs a changelog.

**Comment by luisdavim** [comment]
Sorry, I didn't noticed the changelog was missing.

**Review by majormoses — APPROVED** [review]

**Comment by luisdavim** [comment]
And here's the test artifact:
```
$ /opt/sensu/embedded/bin/ruby /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-sensu-2.3.1/bin/check-aggregate.rb -a http://localhost:4567 -c dcos-check-agent-node-health-aggregate -s --warning_count 1 --critical_count 1 -l 1 -A 120
CheckAggregate OK: Aggregate looks Good

$ /opt/sensu/embedded/bin/ruby /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-sensu-2.3.1/bin/check-aggregate.rb -a http://localhost:4567 -c dcos-check-agent-node-health-aggregate -s --warning_count 1 --critical_count 1 -l 1 -A 120 --debug
CheckAggregate OK: Aggregate looks GOOD
{:ok=>3, :warning=>0, :critical=>0, :unknown=>0, :total=>3, :stale=>0}
```

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-sensu/versions/2.4.0

**Pull request merged**
